# Conclusion {-}

In this thesis, I have provide an overview of the prevalent and crucial roles that cell metabolism plays in a wide spectrum of biological contexts and described the value of genome-scale metabolic modeling integrated with omic data as a generic framework for metabolic research. I first described my effort to comprehensively evaluate and further improve the metabolic transformation algorithm which can be used for causal factor/perturbation identification as well as therapeutic target prediction. Having comprehensively validated the good performance of the algorithm with a large number of validation datasets, I then demonstrated application of the genome-scale metabolic modeling framework, especially with the metabolic transformation algorithm, in two extensive case studies. In the first case, I studied the metabolic processes that regulates the anti-cancer function of CD8 T cells in cancer immunotherapies, where metabolic modeling analysis identified the mitochondrial uncoupling protein UCP2 as essential for CD8 T cell anti-cancer function. Further experimental validation confirmed the effect of Ucp2 in a mice model and showed that Ucp2 regulates CD8 T cell stemness via modulating reactive oxygen species levels. In the second study, I investigated the host metabolic alterations during SARS-CoV-2 infection and predicted anti-SARS-CoV-2 targets that act via reversing the virus-induced host metabolic reprogramming. The predicted single targets and combinatory targets with remdesivir were validated computationally based on published results of large-scale drug and genetic screens for anti-SARS-CoV-2 drug/target discovery. In both cases, the metabolic modeling approach was shown effective in revealing relevant and previously unknown metabolic feactures, which contributes to a deeper understanding of the role of cell metabolism in the respective system under study. More importantly, the findings in both cases are directly translatable to guide the development and optimization of disease therapeutics. This showcases the value and power of the genome-scale metabolic modeling framework in gaining novel and translational insights for the research in various fields related to cell metabolism.
